---
- name: mkdir srcdir
  command: mkdir {{ terraform_srcdir }}
  creates: '{{ terraform_srcdir }}'

- name: Download terraform
  get_url:
    url: {{ terraform_url }}
    dest: {{ terraform_local_file }}
    owner: root
    group: root
    mode: 0644

- name: get Terraform version
  shell: /usr/bin/terraform --version | grep "^Terraform" | cut -f2 -dv
  register: terraform_installed_version
  ignore_errors: yes
  changed_when: false
  failed_when: false

- name: Extract terraform
  command:
    cmd: unzip -o {{ terraform_local_file }} -d /usr/bin
    chdir: '{{ terraform_srcdir }}'
  when: terraform_installed_version.stdout != "{{ terraform_version }}"
